### ISSUE TITLE
Polkit functionality breaks on release builds

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/cosmic-osd#18]
Not sure why this is, but for some reason [ `let session = LogindSessionProxy::new(system_connection).await?;`](https://github.com/pop-os/cosmic-osd/blob/bc35c944e3f4c8bb98b963f8e150830838333ced/src/subscriptions/polkit_agent.rs#L175C5-L175C69)   fails and returns `Failed to create session connection: name already taken on the bus` This only happens on release builds however, debug builds work fine.

**Comment by ids1024** [comment]
This should be fixed with https://github.com/pop-os/iced/pull/114 and 0ca52b5.
