### ISSUE TITLE
OSD volume values syncing

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-osd#23]
The OSD jumps from 0 to 27 when the applet is at 2% and volume is low.

**Comment by leb-kuchen** [comment]
For it me it seems, that the audio applet does not correctly display the audio and the osd displays it correctly

**Comment by ids1024** [comment]
It looks like the applet is using `VolumeLinear`, while generally you want to display volumes in decibels, which better match human perception of volume. (And I think the OSD is currently doing that correctly.)

**Comment by WatchMkr** [comment]
Issue created here: https://github.com/pop-os/cosmic-applets/issues/335
