### ISSUE TITLE
Keyboard brightness OSD does not appear on the darp8

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-osd#25]

**Comment by ids1024** [comment]
Hm, I see `org.freedesktop.UPower.KbdBacklight` isn't sending `BrightnessChanged` on the gaze15, but Gnome is able to  show an OSD.

Need to see what `org.gnome.SettingsDaemon.Power.Keyboard` is doing.

**Comment by ids1024** [comment]
Hm, no udev events, but inotify monitoring of `/sys/class/leds/system76_acpi::kbd_backlight/brightness_hw_changed` works. Not sure what Gnome is doing.

**Comment by WatchMkr** [comment]
OSDs are working on the darp8 now.
