### ISSUE TITLE
OSD is not visible when using the volume slider available in headphones

### ISSUE THREAD

**Issue by senntore** [pop-os/cosmic-osd#36]

**Comment by ids1024** [comment]
The OSD should show any change in volume of the default pulseaudio/pipewire sink device.

If the headphones have a volume control that doesn't show an OSD, but does change the volume, that's probably something that's internal to the headphones and not exposed to the OS?

(In contrast to headphones that just send a button press event for the OS to handle.)

So I'm not sure there's anything to change here. But if it does show an OSD on a different desktop, what headphones, and what desktop does it work on?

**Comment by senntore** [comment]
You're correct. It seems that the volume slider/wheel of my headphone works separately & only adjusts volume of the headphone rather than the master volume of the system.
And yes I also do not see the osd in Gnome when changing volume through the slider.
