### ISSUE TITLE
Audio OSD: when the sound is muted, changing the volume don't unmute

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-osd#37]

**Comment by jacobgkau** [comment]
Confirmed, still occurring on b5eac0e.

If we're really not going to un-mute when the user attempts to change the volume, then the OSD should at least indicate that it's muted instead of showing a number/slider like it's not. But the expected behavior is probably just to unmute on volume change.

**Comment by ids1024** [comment]
Yeah.

In KDE, the audio applet has a separate mute toggle, like alsa/pulse/etc. have internally. Gnome however collapses "muted" and "0 volume" to be equivalent. We probably want to threat it the same way Gnome does, and make sure it's consistent in the OSD/applet/keybindings. (Or we change the design to expose mute status separately like KDE.)

**Comment by jacobgkau** [comment]
I'm not sure if you're just talking about how it works under-the-hood, but on Plasma 6 (and older versions), if I have my output muted and I press the Volume Up or Volume Down key on my keyboard, it gets un-muted. Same behavior as GNOME as far as the OSD is concerned.

**Comment by ids1024** [comment]
I think `cosmic-applet-audio` already works how we want it to, and https://github.com/pop-os/cosmic-settings-daemon/pull/34 and https://github.com/pop-os/cosmic-osd/pull/47 should ensure the OSDs and keybindings are consistent.

**Comment by jacobgkau** [comment]
https://github.com/pop-os/cosmic-settings-daemon/pull/34 alone is enough to consider this issue resolved. Volume is now un-muted when changed, whether via the slider or the keyboard shortcuts.

I tried to test #47. From what's described in that one, I don't think it should have any effect with https://github.com/pop-os/cosmic-settings-daemon/pull/34 (as the case of the OSD showing up for a volume change while muted no longer occurs), and I didn't notice any change. After downgrading `cosmic-settings-daemon` to what's currently released (to try and test without https://github.com/pop-os/cosmic-settings-daemon/pull/34), no keyboard shortcuts seemed to work-- I don't know if that's related to these two changes, or something unrelated that doesn't downgrade cleanly. It does sound like it makes sense to do, anyway.

**Comment by ids1024** [comment]
Yeah, https://github.com/pop-os/cosmic-osd/pull/47 won't really change the behavior when setting volume through key bindings, but will prevent it from making the volume look unmuted when it isn't if you change it with something else (alsamixer, etc.).
