### ISSUE TITLE
Feature Request: Brightness percentage

### ISSUE THREAD

**Issue by rrahl0** [pop-os/cosmic-osd#41]
Please add an option to show Brightness percentage rather than the Candela unit.

**Comment by senntore** [comment]
Yes! Right now the increase & decrease is not noticeable in the slider. See the screenshot below, the brightness is not at the max, yet the slider is near the end.
![screenshot-2024-06-04-05-08-55](https://github.com/pop-os/cosmic-osd/assets/58325574/2fa20655-5c25-4bd4-ba88-fa9726a95062)

**Comment by pknepps** [comment]
This change will probably need to be done in hand with cosmic-settings-daemon

**Comment by mttmartin** [comment]
I created a PR in `cosmic-settings-daemon` (https://github.com/pop-os/cosmic-settings-daemon/pull/32) which would expose the brightness in percent there and would fix this I think.
